// src/utils/apiPaths.js
export const API_PATHS = {
  // Clubs
  CLUBS_LIST: "/clubs/clubs/",
  CLUBS_CREATE: "/clubs/clubs/",
  CLUB_UPDATE: (id) => `/clubs/clubs/${id}`,
  CLUB_DELETE: (id) => `/clubs/clubs/${id}`,
  CLUB_TOGGLE_ACCESS: (id) => `/clubs/clubs/${id}/toggle-access`,

  // Users / Coaches
  COACHES_LIST: "/users/users/coaches",
  COACH_GET: (id) => `/users/users/coaches/${id}`,
  COACH_CREATE: "/users/users/create-coach",
  COACH_UPDATE: (id) => `/users/users/coaches/${id}`,
  COACH_DELETE: (id) => `/users/users/coaches/${id}`,
  CLUB_HEAD_COACH_ASSIGN: (clubId) => `/users/users/clubs/${clubId}/head-coach`,

  // Drills (public lists)
  DRILLS_LIST: "/drills",
  DRILLS_LIST_ALIAS: "/drills/drills",

  // Coach
  DRILLS_MY: "/drills/my",
  DRILLS_MY_ALIAS: "/drills/drills/my",

  // Admin - pending
  DRILLS_PENDING: "/drills/drills/admin/pending",
  DRILLS_PENDING_ALIAS: "/drills/admin/pending",

  // Admin - decision
  DRILL_DECISION: (id) => `/drills/admin/${id}/decision`,
  DRILL_DECISION_ALIAS: (id) => `/drills/drills/admin/${id}/decision`,

  // Single drill (GET)
  DRILL_GET: (id) => `/drills/${id}`,
  DRILL_GET_ALIAS: (id) => `/drills/drills/${id}`,

  // Admin update/delete
  DRILL_UPDATE: (id) => `/drills/${id}`,
  DRILL_DELETE: (id) => `/drills/${id}`,

  // ✅ Trainings (Swagger: POST /trainings/)
  TRAININGS_CREATE: "/trainings/",
  TRAININGS_LIST_MY: "/trainings/my", // ако имаш такъв endpoint – ако не, махни

  // AI training generator
  AI_TRAINING_GENERATE: "/api/ai/training/generate",
  AI_TRAINING_GENERATE_AND_SAVE: "/api/ai/training/generate-and-save",
  AI_TRAINING_FOR_DAY: "/api/ai/training/for-day",

  // Assessment (Национална диагностична карта)
  ASSESSMENT_BATTERY: "/api/assessments/battery",
  ASSESSMENT_WINDOWS: "/api/assessments/windows",
  ASSESSMENT_SESSIONS: "/api/assessments/sessions",
  ASSESSMENT_SESSION_GET: (sessionId) => `/api/assessments/sessions/${sessionId}`,
  ASSESSMENT_RESULTS_BULK: (sessionId) => `/api/assessments/sessions/${sessionId}/results/bulk`,
  ASSESSMENT_SESSION_FINALIZE: (sessionId) => `/api/assessments/sessions/${sessionId}/finalize`,
  ASSESSMENT_DEVELOPMENT: (athleteId) => `/api/assessments/athletes/${athleteId}/development`,
  ASSESSMENT_RESULTS: (athleteId) => `/api/assessments/athletes/${athleteId}/results`,
  ASSESSMENT_TALENT_PROFILE: (athleteId) => `/api/assessments/athletes/${athleteId}/talent-profile`,
  ASSESSMENT_MOTIVATION: (athleteId) => `/api/assessments/athletes/${athleteId}/motivation`,
  ASSESSMENT_AGE_EQUIVALENT: (athleteId) => `/api/assessments/athletes/${athleteId}/age-equivalent`,
  ASSESSMENT_SCOUTING: "/api/assessments/scouting",
  ASSESSMENT_TEAM_INDEX: (teamId) => `/api/assessments/teams/${teamId}/index`,
  ASSESSMENT_RECOMMEND: (athleteId) => `/api/assessments/athletes/${athleteId}/recommend-training`,
  ASSESSMENT_FEDERATION_DASHBOARD: "/api/assessments/federation/dashboard",
  ASSESSMENT_NATIONAL_NORMS: "/api/assessments/national-norms",
  ASSESSMENT_NATIONAL_NORMS_APPROVE: "/api/assessments/national-norms/approve",
  ASSESSMENT_NATIONAL_NORMS_REVOKE: "/api/assessments/national-norms/revoke",
  ASSESSMENT_NATIONAL_NORMS_RECOMPUTE: "/api/assessments/national-norms/recompute",
  ASSESSMENT_CONSENT: (athleteId) => `/api/assessments/athletes/${athleteId}/consent`,
  ASSESSMENT_BATTERY_ADMIN: "/api/assessments/battery/admin",
  ASSESSMENT_BATTERY_AUDIT: "/api/assessments/battery/audit",
  ASSESSMENT_BATTERY_CREATE: "/api/assessments/battery",
  ASSESSMENT_BATTERY_UPDATE: (code) => `/api/assessments/battery/${encodeURIComponent(code)}`,
  ASSESSMENT_BATTERY_DELETE: (code) => `/api/assessments/battery/${encodeURIComponent(code)}`,

  // Articles
  ARTICLES_LIST: "/api/articles",
  ARTICLE_MINE: "/api/articles/mine",
  ARTICLE_GET: (id) => `/api/articles/${id}`,
  ARTICLE_CREATE: "/api/articles",
  ARTICLE_UPDATE: (id) => `/api/articles/${id}`,
  ARTICLE_RESUBMIT: (id) => `/api/articles/${id}/resubmit`,
  ARTICLE_MEDIA_UPLOAD: (id) => `/api/articles/${id}/media`,
  ARTICLE_MEDIA_DELETE: (id, mediaId) => `/api/articles/${id}/media/${mediaId}`,
  ARTICLE_LINK_CREATE: (id) => `/api/articles/${id}/links`,
  ARTICLE_LINK_DELETE: (id, linkId) => `/api/articles/${id}/links/${linkId}`,

  ADMIN_ARTICLES_LIST: "/api/admin/articles",
  ADMIN_ARTICLES_LIST_ALL: "/api/admin/articles",
  ADMIN_ARTICLE_APPROVE: (id) => `/api/admin/articles/${id}/approve`,
  ADMIN_ARTICLE_REJECT: (id) => `/api/admin/articles/${id}/reject`,
  ADMIN_ARTICLE_NEEDS_EDIT: (id) => `/api/admin/articles/${id}/needs-edit`,
  ADMIN_ARTICLE_UPDATE: (id) => `/api/admin/articles/${id}`,
  ADMIN_ARTICLE_DELETE: (id) => `/api/admin/articles/${id}`,
  ADMIN_ANALYTICS_OVERVIEW: "/api/admin/analytics/overview",

  // Forum
  FORUM_POSTS_LIST: "/api/forum/posts",
  FORUM_POST_CREATE: "/api/forum/posts",
  FORUM_POST_GET: (id) => `/api/forum/posts/${id}`,
  FORUM_POST_UPDATE: (id) => `/api/forum/posts/${id}`,
  FORUM_POST_DELETE: (id) => `/api/forum/posts/${id}`,
  FORUM_POST_MODERATION: (id) => `/api/forum/posts/${id}/moderation`,
  FORUM_POST_MEDIA_UPLOAD: (id) => `/api/forum/posts/${id}/media`,
  FORUM_POST_MEDIA_DELETE: (id, mediaId) => `/api/forum/posts/${id}/media/${mediaId}`,
  FORUM_POST_FOLLOW: (id) => `/api/forum/posts/${id}/follow`,
  FORUM_CATEGORIES: "/api/forum/categories",
  FORUM_TAGS: "/api/forum/tags",
  FORUM_NOTIFICATIONS: "/api/forum/notifications",
  NAVBAR_FEED: "/api/navbar/feed",
  PUBLIC_PILOT_REQUEST: "/api/public/pilot-requests",
  PILOT_REQUESTS: "/api/pilot-requests",
  PILOT_REQUEST_UPDATE: (id) => `/api/pilot-requests/${id}`,
  PILOT_REQUESTS_READ_ALL: "/api/pilot-requests/read-all",
  FORUM_NOTIFICATION_READ: (notificationId) => `/api/forum/notifications/${notificationId}/read`,
  FORUM_NOTIFICATIONS_READ_ALL: "/api/forum/notifications/read-all",
  FORUM_REPLY_CREATE: (postId) => `/api/forum/posts/${postId}/replies`,
  FORUM_REPLY_UPDATE: (postId, replyId) => `/api/forum/posts/${postId}/replies/${replyId}`,
  FORUM_REPLY_DELETE: (postId, replyId) => `/api/forum/posts/${postId}/replies/${replyId}`,

  // Monthly fees
  FEES_ATHLETES_LIST: "/api/fees/athletes",
  FEES_ATHLETE_CREATE: "/api/fees/athletes",
  FEES_ATHLETES_IMPORT: "/api/fees/athletes/import",
  FEES_ATHLETES_IMPORT_TEMPLATE: "/api/fees/athletes/import-template",
  FEES_COACHES_LIST: "/api/fees/coaches",
  FEES_ATHLETE_UPDATE: (athleteId) => `/api/fees/athletes/${athleteId}`,
  FEES_ATHLETE_DELETE: (athleteId) => `/api/fees/athletes/${athleteId}`,
  FEES_ATHLETE_TRANSFER: (athleteId) => `/api/fees/athletes/${athleteId}/transfer`,
  FEES_PAYMENT_SAVE: (athleteId) => `/api/fees/athletes/${athleteId}/payments`,
  FEES_ATHLETE_REPORT: (athleteId) => `/api/fees/athletes/${athleteId}/payments`,
  FEES_PERIOD_REPORT: "/api/fees/reports/period",
  FEES_PAYMENT_RECEIPT: (paymentId) => `/api/fees/payments/${paymentId}/receipt.pdf`,
  FEES_PAYMENT_ACTIVITY: "/api/fees/payments/activity",

  // Teams
  TEAMS_LIST: "/api/teams",
  TEAM_CREATE: "/api/teams",
  TEAM_UPDATE: (teamId) => `/api/teams/${teamId}`,
  TEAM_ASSIGN_COACH: (teamId) => `/api/teams/${teamId}/assign-coach`,
  TEAM_DELETE: (teamId) => `/api/teams/${teamId}`,
  TEAM_MEMBERS_GET: (teamId) => `/api/teams/${teamId}/members`,
  TEAM_MEMBERS_SET: (teamId) => `/api/teams/${teamId}/members`,
  TEAM_ATTENDANCE_GET: (teamId) => `/api/teams/${teamId}/attendance`,
  TEAM_ATTENDANCE_SAVE: (teamId) => `/api/teams/${teamId}/attendance`,
  TEAM_ATTENDANCE_REPORT: (teamId) => `/api/teams/${teamId}/attendance/report`,
  TEAM_ATTENDANCE_MATRIX: (teamId) => `/api/teams/${teamId}/attendance/matrix`,
  TEAM_SHEET_PDF: (teamId) => `/api/teams/${teamId}/team-sheet.pdf`,
  TEAM_MATCHES: (teamId) => `/api/teams/${teamId}/matches`,
  TEAM_MATCH: (teamId, matchId) => `/api/teams/${teamId}/matches/${matchId}`,
  TEAM_MATCH_ROSTER: (teamId, matchId) => `/api/teams/${teamId}/matches/${matchId}/roster`,
  TEAM_MATCH_LINEUP: (teamId, matchId) => `/api/teams/${teamId}/matches/${matchId}/lineup`,
  TEAM_MATCH_LIVE: (teamId, matchId) => `/api/teams/${teamId}/matches/${matchId}/live`,
  TEAM_MATCH_LIVE_START: (teamId, matchId) => `/api/teams/${teamId}/matches/${matchId}/live/start`,
  TEAM_MATCH_LIVE_SCORE: (teamId, matchId) => `/api/teams/${teamId}/matches/${matchId}/live/score`,
  TEAM_MATCH_LIVE_STAT: (teamId, matchId) => `/api/teams/${teamId}/matches/${matchId}/live/stat`,
  TEAM_MATCH_LIVE_UNDO: (teamId, matchId) => `/api/teams/${teamId}/matches/${matchId}/live/undo`,
  TEAM_MATCH_LIVE_NEXT_SET: (teamId, matchId) => `/api/teams/${teamId}/matches/${matchId}/live/next-set`,
  TEAM_MATCH_LIVE_FINISH: (teamId, matchId) => `/api/teams/${teamId}/matches/${matchId}/live/finish`,
  TEAM_ATHLETE_PROFILE: (athleteId) => `/api/teams/athletes/${athleteId}/profile`,
  PARENT_AUTH_LOGIN: "/api/parent-auth/login",
  ATHLETE_ROOM_AUTH_LOGIN: "/api/athlete-room-auth/login",
  ATHLETE_ROOM_ME: "/api/athlete-room/me",
  ATHLETE_ROOM_ME_SCHEDULE: "/api/athlete-room/me/schedule",
  ATHLETE_ROOM_DEVELOPMENT_ME: "/api/athlete-room/me/development",
  ATHLETE_ROOM_ACK_CHANGE_ME: "/api/athlete-room/me/ack-change",
  ATHLETE_ROOM_PUSH_VAPID: "/api/athlete-room/push/vapid-public-key",
  ATHLETE_ROOM_PUSH_STATUS_ME: "/api/athlete-room/me/push-status",
  ATHLETE_ROOM_PUSH_SUBSCRIBE_ME: "/api/athlete-room/me/push-subscription",
  ATHLETE_ROOM_PUSH_TEST_ME: "/api/athlete-room/me/push-test",
  ATHLETE_ROOM_CHAT_CHANNELS: "/api/athlete-room/me/chat/channels",
  ATHLETE_ROOM_CHAT_MESSAGES: (teamId) => `/api/athlete-room/me/chat/${teamId}/messages`,
  ATHLETE_ROOM_CHAT_READ: (teamId) => `/api/athlete-room/me/chat/${teamId}/read`,
  ATHLETE_ROOM_CHAT_MESSAGES_READ: (teamId) => `/api/athlete-room/me/chat/${teamId}/messages/read`,
  TEAM_CHAT_MESSAGE_READS: (teamId, messageId) => `/api/teams/${teamId}/chat/messages/${messageId}/reads`,
  TEAM_CHAT_MESSAGES: (teamId) => `/api/teams/${teamId}/chat/messages`,
  TEAM_CHAT_MESSAGE_DELETE: (teamId, messageId) => `/api/teams/${teamId}/chat/messages/${messageId}`,
  PARENT_PORTAL_ME: "/api/parent-portal/me",
  PARENT_PORTAL_ME_SCHEDULE: "/api/parent-portal/me/schedule",
  PARENT_PORTAL_ACK_CHANGES_ME: "/api/parent-portal/me/ack-changes",
  PARENT_PORTAL_ACK_CHANGES_TOKEN: (token) => `/api/parent-portal/${token}/ack-changes`,
  PARENT_PORTAL_ACK_CHANGE_ME: "/api/parent-portal/me/ack-change",
  PARENT_PORTAL_ACK_CHANGE_TOKEN: (token) => `/api/parent-portal/${token}/ack-change`,
  FEES_REMIND_UNPAID: "/api/fees/remind-unpaid",
  PARENT_PUSH_VAPID: "/api/parent-portal/push/vapid-public-key",
  PARENT_PUSH_STATUS_ME: "/api/parent-portal/me/push-status",
  PARENT_PUSH_SUBSCRIBE_ME: "/api/parent-portal/me/push-subscription",
  PARENT_PUSH_TEST_ME: "/api/parent-portal/me/push-test",
  PARENT_PUSH_STATUS_TOKEN: (token) => `/api/parent-portal/${token}/push-status`,
  PARENT_PUSH_SUBSCRIBE_TOKEN: (token) => `/api/parent-portal/${token}/push-subscription`,
  PARENT_PUSH_TEST_TOKEN: (token) => `/api/parent-portal/${token}/push-test`,
  PARENT_PORTAL_GET: (token) => `/api/parent-portal/${token}`,
  PARENT_PORTAL_DEVELOPMENT_ME: "/api/parent-portal/me/development",
  PARENT_PORTAL_DEVELOPMENT_TOKEN: (token) => `/api/parent-portal/${token}/development`,
  PARENT_PORTAL_SCHEDULE: (token) => `/api/parent-portal/${token}/schedule`,
  PARENT_PORTAL_ABSENCE_NOTICES_ME: "/api/parent-portal/me/absence-notices",
  PARENT_PORTAL_ABSENCE_NOTICE_ME: (id) => `/api/parent-portal/me/absence-notices/${id}`,
  PARENT_PORTAL_ABSENCE_NOTICES_TOKEN: (token) => `/api/parent-portal/${token}/absence-notices`,
  PARENT_PORTAL_ABSENCE_NOTICE_TOKEN: (token, id) => `/api/parent-portal/${token}/absence-notices/${id}`,

  TEAM_PORTAL_ITEMS_LIST: (teamId) => `/api/teams/${teamId}/team-portal/items`,
  TEAM_PORTAL_TEXT_CREATE: (teamId) => `/api/teams/${teamId}/team-portal/items/text`,
  TEAM_PORTAL_IMAGE_CREATE: (teamId) => `/api/teams/${teamId}/team-portal/items/image`,
  TEAM_PORTAL_ITEM_DELETE: (teamId, itemId) => `/api/teams/${teamId}/team-portal/items/${itemId}`,

  // Club head coach
  CLUB_OVERVIEW: "/api/club/overview",
  CLUB_ATHLETES: "/api/club/athletes",
  CLUB_FEES_SUMMARY: "/api/club/fees/summary",
  CLUB_ATTENDANCE_SUMMARY: "/api/club/attendance/summary",
  CLUB_TRAININGS: "/api/club/trainings",
  CLUB_REPORT_FEES_XLSX: "/api/club/reports/fees.xlsx",
  CLUB_REPORT_FEES_PDF: "/api/club/reports/fees.pdf",
  CLUB_REPORT_ATTENDANCE_XLSX: "/api/club/reports/attendance.xlsx",
  CLUB_REPORT_ATTENDANCE_PDF: "/api/club/reports/attendance.pdf",

  // Training assignments
  CLUB_TRAINING_ASSIGNMENTS_LIST: "/api/club/training-assignments",
  CLUB_TRAINING_ASSIGNMENTS_CREATE: "/api/club/training-assignments",
  CLUB_TRAINING_ASSIGNMENTS_ACTIVITY: "/api/club/training-assignments/activity",
  MY_TRAINING_ASSIGNMENTS: "/api/trainings/assignments/my",
  TRAINING_ASSIGNMENT_UPDATE: (assignmentId) => `/api/trainings/assignments/${assignmentId}`,
  TRAINING_ASSIGNMENT_DELETE: (assignmentId) => `/api/trainings/assignments/${assignmentId}`,

  // Training schedule calendar
  SCHEDULE_OCCURRENCES: "/api/schedule",
  COACH_ABSENCE_NOTICES: "/api/coach/absence-notices",
  SCHEDULE_RULES_LIST: "/api/schedule/rules",
  SCHEDULE_RULES_CREATE: "/api/schedule/rules",
  SCHEDULE_RULE_UPDATE: (ruleId) => `/api/schedule/rules/${ruleId}`,
  SCHEDULE_RULE_DELETE: (ruleId) => `/api/schedule/rules/${ruleId}`,
  SCHEDULE_EXCEPTION_CREATE: (ruleId) => `/api/schedule/rules/${ruleId}/exceptions`,
  SCHEDULE_EXCEPTION_DELETE: (exceptionId) => `/api/schedule/exceptions/${exceptionId}`,
  SCHEDULE_COMPETITIONS_LIST: "/api/schedule/competitions",
  SCHEDULE_COMPETITION_CREATE: "/api/schedule/competitions",
  SCHEDULE_COMPETITION_UPDATE: (eventId) => `/api/schedule/competitions/${eventId}`,
  SCHEDULE_COMPETITION_DELETE: (eventId) => `/api/schedule/competitions/${eventId}`,

  // National method library (BVF)
  NATIONAL_METHOD_META: "/api/national-method/meta",
  NATIONAL_METHOD_COACH_HUB: "/api/national-method/coach-hub",
  NATIONAL_METHOD_COACH_HUB_SECTION: (slug) => `/api/national-method/coach-hub/${slug}`,
  NATIONAL_METHOD_LIBRARY: "/api/national-method/library",
  NATIONAL_METHOD_ANNUAL_CYCLES: "/api/national-method/annual-cycles",
  NATIONAL_METHOD_TEXTBOOK: "/api/national-method/textbook",
  NATIONAL_METHOD_TEXTBOOK_SECTION: (slug) => `/api/national-method/textbook/${encodeURIComponent(slug)}`,
  NATIONAL_METHOD_CONTEXT: "/api/national-method/method-context",
  NATIONAL_METHOD_PROGRAM_WEEK: "/api/national-method/program-week",
  NATIONAL_METHOD_ARTICLE: (id) => `/api/national-method/articles/${id}`,
  NATIONAL_METHOD_ARTICLE_CYCLES: (id) => `/api/national-method/articles/${id}/cycles`,
  NATIONAL_METHOD_CYCLE: (id) => `/api/national-method/cycles/${id}`,
  NATIONAL_METHOD_DRILL: (id) => `/api/national-method/drills/${id}`,
  NATIONAL_METHOD_ADMIN_SOURCES: "/api/national-method/admin/sources",
  NATIONAL_METHOD_ADMIN_SOURCE: (id) => `/api/national-method/admin/sources/${id}`,
  NATIONAL_METHOD_ADMIN_SOURCE_EXTRACT: (id) => `/api/national-method/admin/sources/${id}/extract`,
  NATIONAL_METHOD_ADMIN_ARTICLES: "/api/national-method/admin/articles",
  NATIONAL_METHOD_ADMIN_ARTICLE: (id) => `/api/national-method/admin/articles/${id}`,
  NATIONAL_METHOD_ADMIN_CYCLES: "/api/national-method/admin/cycles",
  NATIONAL_METHOD_ADMIN_CYCLE: (id) => `/api/national-method/admin/cycles/${id}`,
  NATIONAL_METHOD_ADMIN_DRILLS: "/api/national-method/admin/drills",
  NATIONAL_METHOD_ADMIN_DRILL: (id) => `/api/national-method/admin/drills/${id}`,
  NATIONAL_METHOD_ADMIN_IMPORT_LIBRARY: "/api/national-method/admin/import-library",
  NATIONAL_METHOD_ADMIN_SEED_ANNUAL: "/api/national-method/admin/seed-annual-program",
  NATIONAL_METHOD_ADMIN_PURGE_LEGACY: "/api/national-method/admin/purge-legacy-library",
  CLUB_CYCLE_INSTANCES: "/api/national-method/club/cycle-instances",
  CLUB_CYCLE_INSTANCE: (id) => `/api/national-method/club/cycle-instances/${id}`,
  CLUB_CYCLE_INSTANCE_PREVIEW: "/api/national-method/club/cycle-instances/preview",
  CLUB_METHOD_ASSIGNMENTS: "/api/national-method/club/method-assignments",
  MY_METHOD_ASSIGNMENTS: "/api/national-method/method-assignments/my",
  METHOD_ASSIGNMENT_UPDATE: (id) => `/api/national-method/method-assignments/${id}`,
};
